import { test, expect } from "@playwright/test";
test("isolated built release saves custom greetings/colors and renders them on the default frontend",async({page,baseURL})=>{
  test.setTimeout(60000);
  test.skip(process.env.E2E_REAL_BACKEND!=="1","Requires an explicitly isolated backend");
  expect(baseURL).toBe("http://127.0.0.1:18476");
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  await page.addInitScript(()=>localStorage.setItem("language","zh-CN"));
  await page.goto("/dashboard/login");
  await page.locator('input[name="username"]').fill("admin");
  await page.locator('input[name="password"]').fill("admin");
  await page.locator('button[type="submit"]').click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto("/dashboard/settings/appearance");
  await page.getByRole("button",{name:"分时段问候",exact:true}).click();
  for(let index=7;index>1;index--)await page.getByRole("button",{name:"删除问候时段 "+index,exact:true}).click();
  await page.getByLabel("问候开始时间 1",{exact:true}).fill("00:00");
  await page.getByLabel("问候结束时间 1",{exact:true}).fill("00:00");
  for(let index=10;index>1;index--)await page.getByRole("button",{name:"删除问候语 1-"+index,exact:true}).click();
  await page.getByLabel("问候语 1-1",{exact:true}).fill("你好，独立问候配置已生效");
  await page.getByRole("button",{name:"时钟渐变",exact:true}).click();
  for(const name of ["小时起始色","小时结束色"])await page.getByLabel(name,{exact:true}).fill("#123456");
  for(const name of ["分钟起始色","分钟结束色"])await page.getByLabel(name,{exact:true}).fill("#abcdef");
  for(const name of ["秒钟起始色","秒钟结束色"])await page.getByLabel(name,{exact:true}).fill("#010203");
  await page.getByRole("button",{name:"页面特效",exact:true}).click();
  // Disable unrelated effects only in this disposable test installation.
  for(const toggle of await page.locator('section > div:first-child > [role="switch"]:visible').all())if(!["分时段问候","时钟渐变"].includes((await toggle.getAttribute("aria-label"))||"")&&await toggle.isChecked())await toggle.click();
  await page.getByRole("switch",{name:"启用内置美化",exact:true}).click();
  await page.getByRole("button",{name:"保存美化设置",exact:true}).click();
  await expect(page.getByText("美化设置已保存，请刷新默认主题前台查看")).toBeVisible();
  await page.reload();
  await page.getByRole("button",{name:"时钟渐变",exact:true}).click();
  await expect(page.getByLabel("小时结束色",{exact:true})).toHaveValue("#123456");
  await page.goto("/");
  await expect(page.getByText("你好，独立问候配置已生效",{exact:true})).toBeVisible();
  const groups=page.locator('[data-issues-count-animation="true"]');
  await expect(groups.nth(0)).toHaveCSS("color","rgb(18, 52, 86)");
  await expect(groups.nth(1)).toHaveCSS("color","rgb(171, 205, 239)");
  await expect(groups.nth(2)).toHaveCSS("color","rgb(1, 2, 3)");
  await page.reload();
  await expect(page.getByText("你好，独立问候配置已生效",{exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});
