import {test,expect} from "@playwright/test";
import {createServer} from "../../../user/src/test/fixtures";
const asset="/api/v1/logo/assets/"+"d".repeat(64)+".svg";
const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="4" y="4" width="92" height="92" fill="#dc143c"/><path d="M30 25v50m40-50v50M30 50h40" stroke="white" stroke-width="10"/></svg>';
for(const width of [390,1366])for(const variant of ["short","long","no-expiry"])test("logo overlay preserves all content "+width+" "+variant,async({page})=>{
 let show=false;const now=Date.now(),name=variant==="long"?"这是一个非常长而且会发生换行变化的服务器名字-香港优化线路":"HK 测试机器";
 const note=()=>({...(variant==="no-expiry"?{}:{billingDataMod:{startDate:"2026-09-01T00:00:00+08:00",endDate:"2027-09-01T00:00:00+08:00"}}),planDataMod:{trafficVol:"1TB/月",...(show?{providerLogo:{logo:asset}}:{})}});
 await page.setViewportSize({width,height:900});await page.addInitScript(()=>{localStorage.setItem("inline","0");localStorage.setItem("showMap","0");localStorage.setItem("showServices","0")});
 await page.routeWebSocket("**/api/v1/ws/server",ws=>ws.send(JSON.stringify({now,online:1,servers:[createServer({id:11,name,last_active:new Date(now).toISOString(),public_note:JSON.stringify(note())})]})));
 await page.route("**/api/v1/**",r=>{const path=new URL(r.request().url()).pathname;if(path===asset)return r.fulfill({contentType:"image/svg+xml",body:svg});let data:any=[];if(path==="/api/v1/setting")data={config:{language:"zh-CN",site_name:"布局回归"}};if(path.includes("/service"))data={services:{},cycle_transfer_stats:{}};if(path==="/api/v1/server-traffic")data={};return r.fulfill({json:{success:true,data}})});
 const snapshot=()=>page.locator("[data-server-card]").evaluate(el=>{const c=el.getBoundingClientRect();return {height:c.height,items:["[data-server-name]","[data-server-flag]","[data-server-status]","[data-mobile-billing]","[data-server-billing]","[data-metric-label=cpu]","[data-metric-label=memory]"].map(s=>{const r=el.querySelector(s)!.getBoundingClientRect();return [r.x-c.x,r.y-c.y,r.width,r.height]})}});
 await page.goto("/");await expect(page.locator("[data-server-name]")).toHaveText(name);const before=await snapshot();show=true;await page.reload();const image=page.locator("[data-provider-logo]");await expect(image).toBeVisible();await expect.poll(()=>image.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);expect(await snapshot()).toEqual(before);
 const r=await image.boundingBox();const cardRect=await page.locator("[data-server-card]").boundingBox();expect(r!.y).toBeGreaterThanOrEqual(cardRect!.y);if(width===390){expect(r!.height).toBeLessThanOrEqual(32);expect(r!.width).toBeLessThanOrEqual(64)}else{
 const center=await page.locator("[data-server-identity]").evaluate(el=>{const bar=el.querySelector("[data-expiry-progress]")?.getBoundingClientRect();return bar?bar.left+bar.width/2:el.getBoundingClientRect().left+76});expect(Math.abs(r!.x+r!.width/2-center)).toBeLessThan(1);
 }
 await page.screenshot({path:"test-results/logo-layout-"+width+"-"+variant+".png",fullPage:true});
});
for(const width of [390,1366])test("provider groups and live card preview "+width,async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.setViewportSize({width,height:950});
 const now=Date.now();let groups:any[]=[],entries:any[]=[{id:"provider-test",kind:"provider",name:"香港常用云",regions:[],aliases:"HK Cloud",groupId:"",logo:asset,version:1}];
 let server:any={id:11,host:{version:"2.3.5"},name:"卡片实时调整",display_index:0,user_id:1,uuid:"fixture",public_note:JSON.stringify({keep:1,billingDataMod:{startDate:"2026-09-01T00:00:00+08:00",endDate:"2027-09-01T00:00:00+08:00"},planDataMod:{providerLogo:{logo:asset,logoLibraryId:"provider-test",logoLibraryName:"香港常用云"}}}),note:"",enable_ddns:false,hide_for_guest:false};let saves=0;
 await page.routeWebSocket("**/api/v1/ws/server",ws=>ws.send(JSON.stringify({now,online:1,servers:[createServer({id:11,name:server.name,last_active:new Date(now).toISOString()})]})));
 await page.route("**/api/v1/**",async r=>{const path=new URL(r.request().url()).pathname,method=r.request().method();let data:any=[];
 if(path===asset)return r.fulfill({contentType:"image/svg+xml",body:svg});if(path==="/api/v1/profile")data={id:1,username:"admin",role:0};if(path==="/api/v1/setting")data={config:{site_name:"测试",language:"zh-CN"},version:"test"};
 if(path==="/api/v1/logo/library")data=entries;if(path==="/api/v1/logo/groups"){if(method==="POST"){data={...r.request().postDataJSON(),id:"group-1",version:1};groups.push(data)}else data=groups}
 if(path==="/api/v1/logo/groups/group-1"){if(method==="DELETE"){groups=[];entries[0].groupId="";data=null}else{groups[0]={...groups[0],...r.request().postDataJSON(),version:2};data=groups[0]}}
 if(path==="/api/v1/logo/library/provider-test"&&method==="PUT"){entries[0]={...entries[0],...r.request().postDataJSON(),version:2};data={entry:entries[0],updated_servers:0}}
 if(path==="/api/v1/server")data=[server];if(path==="/api/v1/server/11"&&method==="PATCH"){server={...server,...r.request().postDataJSON()};saves++;data=null}
 if(path.includes("/service"))data={services:{},cycle_transfer_stats:{}};if(path==="/api/v1/server-traffic")data={};
 return r.fulfill({json:{success:true,data}})});
 await page.goto("/dashboard/settings/icons");await page.getByRole("button",{name:"新建分组",exact:true}).click();await page.getByLabel("分组名称",{exact:true}).fill("香港常用");await page.getByRole("button",{name:"保存分组",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.locator("[data-library-row]")).toHaveCount(0);
 await page.getByRole("combobox",{name:"厂商分组",exact:true}).click();await page.getByRole("option",{name:"全部分组",exact:true}).click();await page.getByRole("button",{name:"修改 香港常用云",exact:true}).click();await page.getByRole("combobox",{name:"所属厂商分组",exact:true}).click();await page.getByRole("option",{name:"香港常用",exact:true}).click();await page.getByRole("button",{name:"保存",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 await page.goto("/dashboard");await page.getByRole("row").filter({has:page.getByText("卡片实时调整",{exact:true})}).getByRole("button",{name:"编辑服务器",exact:true}).click();
 const dialog=page.getByRole("dialog"),preview=page.frameLocator('iframe[title="服务器卡片实时预览"]'),img=preview.locator("[data-provider-logo]"),editor=dialog.locator("[data-provider-layout-editor]");
 await editor.scrollIntoViewIfNeeded();await expect(img).toBeVisible();await expect(editor).not.toContainText("正在加载");expect(saves).toBe(0);
 await editor.getByLabel("左右偏移",{exact:true}).fill("12");await editor.getByLabel("上下偏移",{exact:true}).fill("-5");await editor.getByLabel("图标大小",{exact:true}).fill("75");await expect(img).toHaveCSS("transform","matrix(0.75, 0, 0, 0.75, 12, -5)");
 await editor.getByRole("button",{name:"电脑端",exact:true}).click();await expect(editor.getByLabel("左右偏移",{exact:true})).toHaveValue("0");await editor.getByLabel("左右偏移",{exact:true}).fill("-8");await editor.getByLabel("图标大小",{exact:true}).fill("125");await expect(img).toHaveCSS("transform","matrix(1.25, 0, 0, 1.25, -8, 0)");
 expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await editor.scrollIntoViewIfNeeded();await editor.screenshot({path:"test-results/provider-layout-editor-"+width+".png"});await editor.getByRole("button",{name:"手机端",exact:true}).click();await expect(editor.getByLabel("左右偏移",{exact:true})).toHaveValue("12");expect(saves).toBe(0);
 await dialog.locator('button[type="submit"]').click();await expect(dialog).toHaveCount(0);expect(saves).toBe(1);expect(JSON.parse(server.public_note)).toMatchObject({keep:1,planDataMod:{providerLogo:{logoLibraryId:"provider-test",logoLayout:{desktop:{x:-8,scale:125},mobile:{x:12,y:-5,scale:75}}}}});
 await page.reload();await page.getByRole("row").filter({has:page.getByText("卡片实时调整",{exact:true})}).getByRole("button",{name:"编辑服务器",exact:true}).click();await expect(editor.getByLabel("左右偏移",{exact:true})).toHaveValue("12");await editor.getByRole("button",{name:"恢复手机端默认",exact:true}).click();await expect(editor.getByLabel("图标大小",{exact:true})).toHaveValue("100");await dialog.press("Escape");expect(saves).toBe(1);
 await page.goto("/dashboard/settings/icons");await page.getByRole("combobox",{name:"厂商分组",exact:true}).click();await page.getByRole("option",{name:"香港常用",exact:true}).click();await expect(page.locator("[data-library-row]")).toHaveCount(1);page.on("dialog",d=>d.accept());await page.getByRole("button",{name:"删除分组",exact:true}).click();await expect(page.locator("[data-library-row]")).toHaveCount(1);expect(entries[0].groupId).toBe("");expect(errors).toEqual([]);
});
