import {test,expect} from "@playwright/test";
import {createServer} from "../../../user/src/test/fixtures";
const origin="http://127.0.0.1:18476";
for(const width of [390,1366])test("offline detail retains recorded state without changing outer cards "+width,async({page,baseURL})=>{
 expect(baseURL).toBe(origin);
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 const now=Date.now(),last=now-3600123;
 const metrics={cpu:87.25,memory:1073741824,swap:0,disk:5368709120,process_count:29,net_in_speed:2048,net_out_speed:1024,tcp_conn:12,udp_conn:0,uptime:90061,load1:2.5,load5:1.5,load15:0.5,net_in_transfer:123456789,net_out_transfer:987654321};
 const recent=Object.fromEntries(Object.entries(metrics).map(([key,value])=>[key,[{ts:last-60000,value:value/2},{ts:last-30000,value},{ts:last,value}]]));
 let hasRecords=true;let online=false;let socket:any;
 const send=()=>socket?.send(JSON.stringify({now:Date.now(),online:online?1:0,servers:[createServer({id:12,name:"Offline QA",last_active:online?new Date().toISOString():"0001-01-01T00:00:00Z"})]}));
 await page.routeWebSocket("**/api/v1/ws/server",ws=>{socket=ws;send()});
 await page.route("**/*",r=>{
  const u=new URL(r.request().url());
  if(u.pathname==="/api/v1/setting")return r.fulfill({json:{success:true,data:{tsdb_enabled:true,config:{language:"zh-CN",custom_code:"",appearance_config:'{"version":1,"enabled":false,"features":{}}'}}}});
  if(u.pathname.endsWith("/last-report"))return r.fulfill({json:{success:true,data:{server_id:12,tsdb_enabled:true,history_days:1,last_report_at:hasRecords?last:undefined,metrics:hasRecords?metrics:{},recent:hasRecords?recent:{}}}});
  if(u.pathname.endsWith("/metrics"))return r.fulfill({json:{success:true,data:{data_points:recent[u.searchParams.get("metric")!]||[]}}});
  if(u.pathname==="/api/v1/profile")return r.fulfill({json:{success:false,error:"guest"}});
  if(u.pathname==="/api/v1/server-group")return r.fulfill({json:{success:true,data:[]}});
  if(u.pathname.includes("/service"))return r.fulfill({json:{success:true,data:{services:{},cycle_transfer_stats:{}}}});
  if(u.origin!==origin)return r.abort();return r.continue();
 });
 await page.setViewportSize({width,height:1000});await page.goto("/");
 await expect(page.getByText("Offline QA",{exact:true})).toBeVisible();
 await expect(page.locator("[data-offline-summary]")).toHaveCount(0);
 await page.getByText("Offline QA",{exact:true}).click();
 await expect(page).toHaveURL(/server\/12$/);
 await expect(page.locator("[data-offline-summary]")).toContainText("1 小时");
 await expect(page.locator("[data-offline-summary] time")).toHaveAttribute("datetime",new Date(last).toISOString());
 await expect(page.getByText("87.25%",{exact:true})).toBeVisible();
 await expect(page.locator("[data-recorded-chart]")).toHaveCount(6);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:"test-results/offline-detail-"+width+".png",fullPage:true});
 await expect(page.getByRole("button",{name:"7 天",exact:true})).toBeDisabled();
 await page.getByRole("button",{name:"1 天",exact:true}).click();await expect(page.locator("[data-recorded-chart]")).toHaveCount(6);
 const offlineChartSize=await page.locator("[data-recorded-chart]").first().boundingBox();
 await expect(page.getByRole("button",{name:"最后状态",exact:true})).toBeVisible();
 online=true;send();await expect(page.locator("[data-offline-detail]")).toHaveCount(0);
 await expect(page.getByRole("button",{name:"实时",exact:true})).toBeVisible();
 const onlineChartSize=await page.locator(".server-charts [data-chart]").first().boundingBox();
 expect(offlineChartSize?.height).toBe(130);expect(onlineChartSize?.height).toBe(130);
 expect(offlineChartSize?.width).toBeCloseTo(onlineChartSize!.width,0);
 online=false;send();await expect(page.locator("[data-offline-summary]")).toBeVisible();
 hasRecords=false;await page.reload();
 await expect(page.locator("[data-offline-empty]")).toContainText("无法确定掉线时间");
 await expect(page.locator("[data-recorded-chart]")).toHaveCount(0);
 await expect(page.getByText("0.00%",{exact:true})).toHaveCount(0);
 await page.screenshot({path:"test-results/offline-detail-empty-"+width+".png",fullPage:true});
 expect(errors).toEqual([]);
});
