import {test,expect} from "@playwright/test";
import {createServer} from "../../../user/src/test/fixtures";
const origin="http://127.0.0.1:18476";
for(const width of [390,1366])test("full offline snapshot matches online host and percentages "+width,async({page,baseURL})=>{
 expect(baseURL).toBe(origin);
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 const now=Date.now(),at=now-90*86400000;
 const host={platform:"ubuntu",platform_version:"24.04",cpu:["AMD Ryzen 9 9950X 4 Virtual Core"],gpu:["RTX QA"],arch:"x86_64",version:"2.3.5",boot_time:Math.floor((at-86400000)/1000),mem_total:8*2**30,disk_total:100*2**30,swap_total:2*2**30};
 const state={cpu:19.25,mem_used:2*2**30,disk_used:25*2**30,swap_used:2**30,uptime:86400,load_1:1.06,load_5:1.05,load_15:1.01,net_in_transfer:285*2**30,net_out_transfer:532*2**30,net_in_speed:2048,net_out_speed:1024,tcp_conn_count:5,udp_conn_count:2,process_count:90,gpu:[42],temperatures:[{Name:"CPU sensor",Temperature:51.5}]};
 const metrics={cpu:state.cpu,memory:state.mem_used,swap:state.swap_used,disk:state.disk_used,memory_percent:25,swap_percent:50,disk_percent:25,uptime:state.uptime,load1:1.06,load5:1.05,load15:1.01,net_in_transfer:state.net_in_transfer,net_out_transfer:state.net_out_transfer,net_in_speed:2048,net_out_speed:1024,tcp_conn:5,udp_conn:2,process_count:90,gpu_0:42};
 const recent=Object.fromEntries(Object.entries(metrics).map(([key,value])=>[key,Array.from({length:21},(_,i)=>({ts:at-60000+i*3000,value}))]));
 let offline=false,socket:any;
 const send=()=>socket?.send(JSON.stringify({now:Date.now(),online:offline?0:1,servers:[createServer({id:12,name:"完整快照 QA",country_code:offline?"":"JP",host:offline?{} as any:host,state:offline?{} as any:state,last_active:offline?"0001-01-01T00:00:00Z":new Date().toISOString()})]}));
 await page.routeWebSocket("**/api/v1/ws/server",ws=>{socket=ws;send()});
 await page.route("**/*",r=>{
  const u=new URL(r.request().url());
  if(u.pathname==="/api/v1/setting")return r.fulfill({json:{success:true,data:{tsdb_enabled:false,config:{language:"zh-CN",custom_code:"",appearance_config:'{"version":1,"enabled":false,"features":{}}'}}}});
  if(u.pathname.endsWith("/last-report"))return r.fulfill({json:{success:true,data:{server_id:12,tsdb_enabled:false,history_days:30,snapshot_seconds:60,last_report_at:at,snapshot:{at,host,state,country_code:"JP"},metrics,recent}}});
  if(u.pathname==="/api/v1/profile")return r.fulfill({json:{success:true,data:{id:1,username:"admin"}}});
  if(u.pathname==="/api/v1/server-group")return r.fulfill({json:{success:true,data:[]}});
  if(u.pathname.includes("/service"))return r.fulfill({json:{success:true,data:{services:{},cycle_transfer_stats:{}}}});
  if(u.origin!==origin)return r.abort();return r.continue();
 });
 await page.setViewportSize({width,height:1000});await page.goto("/server/12");
 await expect(page.getByText("AMD Ryzen 9 9950X 4 Virtual Core",{exact:true})).toBeVisible();
 const details=page.locator(".server-info");
 for(const label of ["2.3.5","x86_64","8.00 GiB","100.00 GiB","ubuntu - 24.04"])await expect(details.getByText(label,{exact:true})).toBeVisible();
 await page.screenshot({path:"test-results/snapshot-online-"+width+".png",fullPage:true});
 offline=true;send();
 await expect(page.locator("[data-offline-summary]")).toBeVisible();
 for(const label of ["2.3.5","x86_64","8.00 GiB","100.00 GiB","ubuntu - 24.04","AMD Ryzen 9 9950X 4 Virtual Core"])await expect(page.locator("[data-offline-summary]").getByText(label,{exact:true})).toBeVisible();
 await expect(details.getByText("2.00 GiB / 8.00 GiB",{exact:true})).toBeVisible();
 await expect(details.getByText("25.00 GiB / 100.00 GiB",{exact:true})).toBeVisible();
 await expect(details.getByText("1.00 GiB / 2.00 GiB",{exact:true})).toBeVisible();
 await expect(details.getByText("25%",{exact:true})).toHaveCount(2);
 await expect(details.locator(".server-charts").getByText("50%",{exact:true}).first()).toBeVisible();
 await expect(page.locator("[data-recorded-chart]")).toHaveCount(7);
 await expect(page.getByRole("button",{name:"1 天",exact:true})).toBeDisabled();
 await expect(page.locator("[data-offline-summary] time")).toHaveAttribute("datetime",new Date(at).toISOString());
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:"test-results/snapshot-offline-"+width+".png",fullPage:true});
 await page.reload();await expect(details.getByText("25.00 GiB / 100.00 GiB",{exact:true})).toBeVisible();
 await expect(details.getByText("未知",{exact:true})).toHaveCount(0);
 expect(errors).toEqual([]);
});
