import {test,expect} from "@playwright/test";
for(const width of [1366,390])test("bilingual note autofill and roundtrip "+width,async({page})=>{
 await page.setViewportSize({width,height:900});
 const original={billingDataMod:{startDate:"2026-06-15T00:00:00+08:00",endDate:"2026-07-15T00:00:00+08:00",autoRenewal:"1",cycle:"月"},planDataMod:{bandwidth:"5000Mbps",trafficVol:"5TB/月",trafficType:"0",IPv4:"1",IPv6:"0",networkRoute:"163PP/CN2,CMI/CMIN2,10099/9929专线",extra:"三网顶级优化",custom:"keep"},unknown:{keep:true}};
 let server:any={id:11,host:{version:"2.3.5"},name:"备注兼容测试",display_index:0,user_id:1,uuid:"fixture",public_note:JSON.stringify(original),note:"",enable_ddns:false,hide_for_guest:false};
 const updates:any[]=[],errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.route("**/api/v1/**",async route=>{
  const path=new URL(route.request().url()).pathname,method=route.request().method();let data:any=[];
  if(path==="/api/v1/profile")data={id:1,username:"admin",role:0};
  if(path==="/api/v1/setting")data={config:{site_name:"测试",language:"zh-CN"},version:"test"};
  if(path==="/api/v1/server")data=[server];
  if(path==="/api/v1/server/11"&&method!=="GET"){const body=route.request().postDataJSON();updates.push(body);server={...server,...body};}
  await route.fulfill({json:{success:true,data}});
 });
 await page.goto("/dashboard");
 const row=page.getByRole("row").filter({has:page.getByText("备注兼容测试",{exact:true})});
 await row.getByRole("button",{name:"编辑服务器",exact:true}).click();
 const dialog=page.getByRole("dialog");
 await expect(dialog.getByLabel("中国电信")).toHaveValue("163PP/CN2");
 await expect(dialog.getByLabel("中国移动")).toHaveValue("CMI/CMIN2");
 await expect(dialog.getByLabel("中国联通")).toHaveValue("10099/9929专线");
 await expect(dialog.getByRole("combobox").filter({hasText:"未指定（默认双向）"})).toBeVisible();
 const ips=dialog.locator("[data-ip-options]");
 await ips.scrollIntoViewIfNeeded();
 await expect.poll(()=>ips.evaluate(el=>{const labels=el.querySelectorAll("label"),a=labels[0].getBoundingClientRect(),b=labels[1].getBoundingClientRect();return Math.abs(a.y-b.y)<2&&b.x>a.x;})).toBe(true);
 await page.screenshot({path:"test-results/ip-options-"+width+".png"});
 await dialog.getByLabel("中国电信").fill("CN2 GIA");
 await dialog.getByLabel("流量重置日",{exact:true}).fill("15");
 await dialog.getByRole("button",{name:"原始文本",exact:true}).click();
 const raw=dialog.getByRole("textbox",{name:"公开备注原始文本"});
 const doc=JSON.parse(await raw.inputValue());
 expect(doc.套餐信息.运营商线路.中国电信).toBe("CN2 GIA");expect(doc.unknown).toEqual({keep:true});
 doc.套餐信息.流量="6TB/月";await raw.fill(JSON.stringify(doc));
 await dialog.getByRole("button",{name:"自定义字段",exact:true}).click();
 await expect(dialog.getByLabel("中国电信")).toHaveValue("CN2 GIA");
 await expect(dialog.locator('input[value="6TB/月"]')).toBeVisible();
 await dialog.getByRole("button",{name:"自定义字段",exact:true}).click();
 await expect(dialog.getByLabel("中国电信")).toHaveValue("CN2 GIA");
 await dialog.getByLabel("中国联通").scrollIntoViewIfNeeded();
 await page.screenshot({path:"test-results/public-note-"+width+".png"});
 await dialog.locator('button[type="submit"]').click();await expect.poll(()=>updates.length).toBe(1);
 const saved=JSON.parse(updates[0].public_note);
 expect(saved.planDataMod).toMatchObject({trafficVol:"6TB/月",trafficType:"0",resetDay:"15",networkRoute:"CN2 GIA,CMI/CMIN2,10099/9929专线",custom:"keep"});
 expect(saved.unknown).toEqual({keep:true});
 await row.getByRole("button",{name:"编辑服务器",exact:true}).click();
 await expect(dialog.getByLabel("中国电信")).toHaveValue("CN2 GIA");
 await dialog.getByRole("button",{name:"原始文本",exact:true}).click();await raw.fill("不是JSON的旧备注");
 await dialog.getByRole("button",{name:"自定义字段",exact:true}).click();await expect(raw).toHaveValue("不是JSON的旧备注");
 expect(errors).toEqual([]);
});
